apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    app.kubernetes.io/instance: edge-nginx
  name: edge-nginx-nodeport
spec:
  ports:
  - port: 8111
    protocol: TCP
    targetPort: 80
    nodePort: 30011
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort 
